DOMAIN = "iclick"
DEFAULT_PORT = 9999
TIMEOUT = 10

CONF_HOST = "host"
CONF_PORT = "port"

ERROR_INVALID_IP = "invalid_ip"
ERROR_CONNECTION_FAILED = "connection_failed"

HEARTBEAT_INTERVAL = 60
MAX_RECONNECT_RETRIES = 5
BASE_RECONNECT_DELAY = 1.0
MAX_RECONNECT_DELAY = 60.0