send_command:
  fields:
    data:
      description: Format example：1-0001 (hub_id-hex data)
      required: true
      selector:
        text:
          pattern: "^[1-9]-[0-9A-Fa-f]+$"  # 正确正则（包含 hub_id）