send_command:
  fields:
    entry_id:
      name: Entry ID
      description: The entry ID of the iClick instance.
      required: true
      example: "abc123def456"
      selector:
        text:
    data:
      description: Format example：xxxx-0001 (hub_id-hex data)
      required: true
      selector:
        text: